### ISSUE TITLE
what's the function of the  mirrored image?

### ISSUE THREAD

**Issue by yichuan9527** [huanghoujing/person-reid-triplet-loss-baseline#10]
Hello, your code is very good.
I have a question. The dataloader returns  mirrored image, but I don't see you use the  mirrored image in triplet loss baseline. What's the function of the  mirrored?

**Comment by huanghoujing** [comment]
The `mirrored` means whether image is mirrored or not. It's a Boolean object, not image. So it's just an indicator.
`mirrored` appears at [1](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/blob/81e81277060752c917bf3743edd6023c320ee42d/tri_loss/dataset/PreProcessImage.py#L121), [2](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/blob/81e81277060752c917bf3743edd6023c320ee42d/tri_loss/dataset/TrainSet.py#L81)

Thanks for your attention.

**Comment by yichuan9527** [comment]
Thanks！
