### ISSUE TITLE
 except Exception, msg:     ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vismayaps** [huanghoujing/person-reid-triplet-loss-baseline#11]
When I tried testing the pre-trained model on market1501 dataset using python3 the given command 
"python script/experiment/train.py \
-d '(0,)' \
--only_test true \
--dataset DATASET_NAME \
--last_conv_stride STRIDE \
--normalize_feature false \
--exp_dir EXPERIMENT_DIRECTORY \
--model_weight_file THE_DOWNLOADED_MODEL_WEIGHT_FILE"
I am getting the error 
"except Exception, msg:
                              ^
SyntaxError: invalid syntax"
and when testing it with python 2.7, I am getting the following error "train.py: error: unrecognized arguments:" 
Any help would be appreciated !!
Thanks !

**Comment by huanghoujing** [comment]
Hi, thanks for your attention. These places `DATASET_NAME`, `STRIDE`, `EXPERIMENT_DIRECTORY`,  `THE_DOWNLOADED_MODEL_WEIGHT_FILE` should be replaced by respective values, e.g. by `market1501`, `1`, `exp`, `model_weight.pth`. You should specify these.

**Comment by vismayaps** [comment]
Hi, I tried every possible combinations to run this but I get this "unrecognised arguments error", can you please post the exact command to run ? name of my experiment directory is "test_log", and the downloaded weight file is inside the folder "market501_stride1".

**Comment by huanghoujing** [comment]
You can share your full command here, and I see if there is a problem.

**Comment by vismayaps** [comment]
Hi, 
Here is the command I am using for testing :
> python script/experiment/train.py  \
> -d '(0,)'  \
> --only_test true  \
> --market1501  \
> --1  \
> --normalize_feature false  \
> --exp  \
> --model_weight.pth
 and I am getting the following error :
usage: train.py [-h] [-d SYS_DEVICE_IDS] [-r RUN] [--set_seed SET_SEED]
                [--dataset {market1501,cuhk03,duke,combined}]
                [--trainset_part {trainval,train}] [--resize_h_w RESIZE_H_W]
                [--crop_prob CROP_PROB] [--crop_ratio CROP_RATIO]
                [--mirror MIRROR] [--ids_per_batch IDS_PER_BATCH]
                [--ims_per_id IMS_PER_ID] [--log_to_file LOG_TO_FILE]
                [--steps_per_log STEPS_PER_LOG]
                [--epochs_per_val EPOCHS_PER_VAL] [--last_conv_stride {1,2}]
                [--normalize_feature NORMALIZE_FEATURE] [--margin MARGIN]
                [--only_test ONLY_TEST] [--resume RESUME] [--exp_dir EXP_DIR]
                [--model_weight_file MODEL_WEIGHT_FILE] [--base_lr BASE_LR]
                [--lr_decay_type {exp,staircase}]
                [--exp_decay_at_epoch EXP_DECAY_AT_EPOCH]
                [--staircase_decay_at_epochs STAIRCASE_DECAY_AT_EPOCHS]
                [--staircase_decay_multiply_factor STAIRCASE_DECAY_MULTIPLY_FACTOR]
                [--total_epochs TOTAL_EPOCHS]
train.py: error: ambiguous option: --exp could match --exp_dir, --exp_decay_at_epoch
Thanks !!

**Comment by huanghoujing** [comment]
OK, (1) you missed the trailing backslashes ` \` for multi-line command. (2) Some keywords are missing in your command. The modified version is as follows. You may try it.
```
python script/experiment/train.py \
-d '(0,)' \
--only_test true \
--dataset market1501 \
--last_conv_stride 1 \
--normalize_feature false \
--exp_dir exp \
--model_weight_file model_weight.pth
```
