### ISSUE TITLE
Any opinions on training this on vehicle re-identification?

### ISSUE THREAD

**Issue by cesarandreslopez** [huanghoujing/person-reid-triplet-loss-baseline#17]
@huanghoujing first of all, great work!

I was wondering if you have any thoughts on training this on-vehicle re-id. I'm about to give it a try, will report results.

**Comment by huanghoujing** [comment]
Triplet loss seems ok for Vehicle ReID, if you have the dataset. Looking forward to your result!

**Comment by cesarandreslopez** [comment]
I do have the dataset, just trying to get it formatted. Will report here once I have it trained! 

Thank you! @huanghoujing

**Comment by wanghonglie** [comment]
> I do have the dataset, just trying to get it formatted. Will report here once I have it trained!
> 
> Thank you! @huanghoujing

hi, have you formatted the vehicle datasets yet?
