### ISSUE TITLE
Compare 2 photographs and get distance based on model

### ISSUE THREAD

**Issue by cesarandreslopez** [huanghoujing/person-reid-triplet-loss-baseline#18]
I've been trying to write up code that would allow me to extract features of a person, given by jpg, extract the features based on the model and then calculate the distance to other features extracted from other person shot.

Any pointers on this would be most appreciated.

**Comment by huanghoujing** [comment]
Hi, thanks for your interest! The common procedure would be
1. Instantiate the model and load the trained model weight
2. Read your image, resize, subtract mean, divide by variance, transform to Variable
3. Feed the image to the model and get the feature
4. Compare feature distance between images

In this way, you don't need to use any Dataset interface of this code and can simply skip it.

**Comment by Pamulapati13** [comment]
hi,this repo is really good.
Can I get the trained model weights or should i train it locally on my PC

**Comment by huanghoujing** [comment]
Hi, you can download the trained models as described in README.
