### ISSUE TITLE
batch怎么组装？三元组怎么挑选？组装好batch时就挑好了三元组？

### ISSUE THREAD

**Issue by exitxingling** [huanghoujing/person-reid-triplet-loss-baseline#19]
你好，我想请问一下，triplet-loss使用 的是三元组数据，那在代码的数据集以batch_size大小的分批次加载数据的时候，也是要加载三元组数据吗？

**Comment by huanghoujing** [comment]
你好，组装batch的时候是不考虑哪些样本会组成三元组的，一个batch包含有P个人、每个人取K张图片，比如P=16，K=4，batch中有64张图片。这些图片都经过网络提取特征，得到64个特征。接下来构建三元组：（1）把每一个图片都当成anchor，总共可以选出64个三元组（其实按照排列组合可以选出很多三元组的，In defense of triplet loss这篇文章就只构建有代表性的64个三元组），（2）每个三元组的anchor选定后，positive从K-1个中选一个与anchor特征距离最远的样本，negative从P\*K-K个中选一个与anchor特征距离最近的样本，这样子对这个anchor来说，选出来的positive和negative都是最困难的。这样组建了P\*K个三元组，计算出P\*K个triplet loss，把这些loss取平均进行反传。

数据集迭代的过程是按照person id来循环的，假设数据集有751个id，一个batch取掉了16个id，这样经过`int(751/16)`个batch就循环了一次（一个epoch），接下来把id的顺序打乱，进行下一轮迭代（下一个epoch）。

**Comment by exitxingling** [comment]
谢谢解答！！
