### ISSUE TITLE
why the results on CUHK03 is much inferior to the paper?

### ISSUE THREAD

**Issue by kailigo** [huanghoujing/person-reid-triplet-loss-baseline#2]
Thank you for sharing the code!

In the paper,  a R1 accuracy of 89.63 is reported on the CUHK03 dataset. But in your implementation, only ~60.0. How does this happen. Thanks.

**Comment by huanghoujing** [comment]
Thank you for your attention!

Here I use new train/test protocol for CUHK03, detail of which can be found [here](https://github.com/zhunzhong07/person-re-ranking). The paper of *In Defense of Triplet Loss...* uses the original CUHK03 train/test splits. That's the difference.
