### ISSUE TITLE
rerank

### ISSUE THREAD

**Issue by chj1933** [huanghoujing/person-reid-triplet-loss-baseline#20]
@huanghoujing ,Hello, if I don't want to use rerank, please tell me how should I set parameters？

**Comment by DengpanFu** [comment]
TestSet( ... ).eval( ... ) has the parameter **to_re_rank**, you can refer to [TestSet.py](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/blob/master/tri_loss/dataset/TestSet.py#L134). You also can refer to 
[train.validate](https://github.com/huanghoujing/person-reid-triplet-loss-baseline/blob/master/script/experiment/train.py#L397) to see how to use eval()
