### ISSUE TITLE
String typeError in Python 3

### ISSUE THREAD

**Issue by mega768** [huanghoujing/person-reid-triplet-loss-baseline#22]
I am using python 3 to run the program but at line 59 im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']] typeError: Can't mix strings and bytes in path components will occur.
Is there a way to change this in python 3?

**Comment by moyu2017** [comment]
I have also encountered this problem,it‘s a Data type mismatch problem.
I judge the type of n with the following codes:
    # im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]    
    for n in partitions['trainval_im_names']:
        if type(n) != str:
            n = n.decode('utf-8')
        im_paths.append(ospj(im_dir, n))
    im_paths.sort()
    ......

**Comment by moyu2017** [comment]
I have also encountered this problem,it‘s a Data type mismatch problem.
I judge the type of n with the following codes:
# im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]    
    for n in partitions['trainval_im_names']:
        if type(n) != str:
            n = n.decode('utf-8')
        im_paths.append(ospj(im_dir, n))
    im_paths.sort()
    ......

**Comment by moyu2017** [comment]
I have also encountered this problem,it‘s a Data type mismatch problem.
I judge the type of n with the following codes:
# im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]    
    for n in partitions['trainval_im_names']:
        if type(n) != str:
            n = n.decode('utf-8')
        im_paths.append(ospj(im_dir, n))
    im_paths.sort()
    ......

**Comment by zengxixiang** [comment]
I have also encountered this problem,it‘s a Data type mismatch problem.
I judge the type of n with the following codes:
    # im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]
    for n in partitions['trainval_im_names']:
        if type(n) != str:
            n = n.decode('utf-8')
        im_paths.append(ospj(im_dir, n))
    im_paths.sort()

**Comment by huanghoujing** [comment]
According to moyu2017, you can replace this line 
```python
im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]
```
with following lines:
```python
for n in partitions['trainval_im_names']:
    if type(n) != str:
        n = n.decode('utf-8')
    im_paths.append(ospj(im_dir, n))
```
I am not sure if it works or not, you may have a try.
