### ISSUE TITLE
Do you add some layer after Resnet50

### ISSUE THREAD

**Issue by LibreAgent2025** [huanghoujing/person-reid-triplet-loss-baseline#25]
I find that you didn't add any conv layer after Resnet50. So, you are trainning Resnet50, which is surprising to my, because normal net just fine-tune Resnet50, and use the after layer to discriminate, like PCB

**Comment by huanghoujing** [comment]
Yes, I do not add extra conv/fc layer after Conv5. Here we directly use globally pooled Conv5 feature vector. You can try to add embedding layer after globally pooled feature, but I find it no better for this baseline.

**Comment by LibreAgent2025** [comment]
thank you

**Comment by LibreAgent2025** [comment]
> Yes, I do not add extra conv/fc layer after Conv5. Here we directly use globally pooled Conv5 feature vector. You can try to add embedding layer after globally pooled feature, but I find it no better for this baseline.

maybe you need to add Queue.py in tri_loss/dataset, because Prefetcher.py import it. But you didn't give it

**Comment by LibreAgent2025** [comment]
> Yes, I do not add extra conv/fc layer after Conv5. Here we directly use globally pooled Conv5 feature vector. You can try to add embedding layer after globally pooled feature, but I find it no better for this baseline.

sorry, my bad. I forget Queue is a baisc module
