### ISSUE TITLE
"val" set for combined dataset

### ISSUE THREAD

**Issue by liliangqi** [huanghoujing/person-reid-triplet-loss-baseline#4]
Hi, there is an obvious error about "val" set for the combined dataset.  In `script/experiment/train.py`, you set `part='val'`  at Line 165 and use that to create `val_set` at Line 324. However, in `tri_loss/dataset/__init__.py`, there is `assert part in ['trainval'], "Only trainval part of the combined dataset is available now."` at Line 40. So, this is a conflict and if I fix with `part='trainval'` at Line 165 in `train.py`, there will be much more problems.

**Comment by huanghoujing** [comment]
Thank you for your question. This is my mistake. I do not separate a validation part from the combined dataset, so when using the combined dataset for training, anything about validation set should be commented in `train.py`. You may comment lines like `val_set = create_dataset(**cfg.val_set_kwargs)` etc to solve the problem.

**Comment by liliangqi** [comment]
@huanghoujing Thanks for your response.
