### ISSUE TITLE
损失函数是不是可以更直接呢

### ISSUE THREAD

**Issue by CynicalHeart** [huanghoujing/person-reid-triplet-loss-baseline#41]
TripletLoss 里面根据margin传入与否使用了MarginRankingLoss/SoftMarginLoss()。我看了几个Triplet-Loss的代码，大家都避开直接使用TripletMarginLoss和TripletMarginWithDistanceLoss，这到底是为什么呀。

**Comment by huanghoujing** [comment]
你好，感谢你对本代码的关注。这份代码采用`MarginRankingLoss`和`SoftMarginLoss`，是借鉴于open-reid项目。当时Pytorch处于v0.2、v0.3这样的低版本，因此`TripletMarginLoss`这些类还没有广泛使用。后续既然`MarginRankingLoss`和`SoftMarginLoss`可以用了，所以也就没有特意改成`TripletMarginLoss`这些。

**Comment by CynicalHeart** [comment]
> 你好，感谢你对本代码的关注。这份代码采用`MarginRankingLoss`和`SoftMarginLoss`，是借鉴于open-reid项目。当时Pytorch处于v0.2、v0.3这样的低版本，因此`TripletMarginLoss`这些类还没有广泛使用。后续既然`MarginRankingLoss`和`SoftMarginLoss`可以用了，所以也就没有特意改成`TripletMarginLoss`这些。

感谢回复。近期学习了不少代码，现在我觉得`MarginRankingLoss`更具有泛用性，它需要输入正负例与anchor的距离，而不是像`TripletMarginLoss`那样直接输入样本，这样方便统计准确率，同时能编写验证phase。用`MarginRankingLoss`和`SoftMarginLoss`虽然方便，但是直接出loss没办法统计准确率，让人苦恼。
