### ISSUE TITLE
About evaluation metric

### ISSUE THREAD

**Issue by kentang-mit** [huanghoujing/person-reid-triplet-loss-baseline#5]
Hello sir,
  Thanks for your terrific implementation of triplet-loss-based person re-id method! I have a small question about the evaluation metric. As is pointed out by your document, the evaluation code is borrowed from Open Re-ID project(https://github.com/Cysu/open-reid).
  In the open re-id project, it seems that some images(to be specific, those with id -1) in the original "bounding_box_test" folder are ignored while calculating CMC/MAP. I found when these images are added, the CMC1 drops from 87%+ to around 80%. I wonder whether the evaluation part of most person re-id papers also ignore these distractors with label -1.
  I would be very appreciated for your reply.
Best wishes!

**Comment by huanghoujing** [comment]
Yes, id -1 is totally useless in evaluation and images of which are not used at all.

Reference from [Market-1501](http://www.liangzheng.org/Project/project_reid.html):
>1. What are images beginning with "0000" and "-1"? 
Ans: Names beginning with "0000" are distractors produced by DPM false detection.
Names beginning with "-1" are junks that are neither good nor bad DPM bboxes.
So "0000" will have a negative impact on accuracy, while "-1" will have no impact. 
During testing, we rank all the images in "bounding_box_test". Then, the junk images are just neglected; distractor images are not neglected.

**Comment by kentang-mit** [comment]
Thanks for your reply ^_^ and I shall close this.
