### ISSUE TITLE
Reasons for better results

### ISSUE THREAD

**Issue by liangbh6** [huanghoujing/person-reid-triplet-loss-baseline#7]
Hi, as we can see from the paper 'In Defense of the Triplet Loss for Person Re-Identification', rank1 on Market1501 without test augmentation is 82.51%, while yours is 86.43%, I doubt that which settings make your network better,  network architecture? batch size ? sampling for a batch?

**Comment by huanghoujing** [comment]
I think the point is
- longer training time
- smaller margin, 0.5 -> 0.3

Other differences may also matter
- I do not add additional fully connected layers after the ResNet backbone
- I do not apply random cropping at training time

Thanks for your watching. If you have any interesting finding in your experiments, feel free to share it in the issues.

**Comment by liangbh6** [comment]
Well, I found that for batch-hard triplet loss
1. better result will be obtained without fc added;
2. smaller batch size will get inferior results, eg, batch_size=72 is better than batch_size=32, but the runtime for smaller batch is shorter.
Your results are attractive. Thanks for your kind reply~

**Comment by huanghoujing** [comment]
Thanks for sharing! Someone may find these useful.
